# Generated by Django 3.2.7 on 2021-09-13 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Curencies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query_date', models.DateTimeField(verbose_name='QueryDate')),
                ('currency', models.CharField(max_length=3, verbose_name='currency')),
                ('final_quote', models.FloatField(verbose_name='final_quote')),
            ],
            options={
                'ordering': ['-query_date', 'currency'],
            },
        ),
    ]
