# Generated by Django 3.2.7 on 2021-09-13 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('converter', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curencies',
            name='currency',
            field=models.CharField(max_length=10, verbose_name='currency'),
        ),
    ]
