# Generated by Django 3.2.7 on 2021-09-13 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('converter', '0002_alter_curencies_currency'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Curencies',
            new_name='Currencies',
        ),
    ]
